BMI/views.py
from models import BMI
from app import db, app
from flask_login import current_user,login_required
from BMI.forms import BMIForm, BMIResultForm
from flask import Blueprint, render_template
from users.views import requires_roles
from BMI.calc_bmi import bmi_calc, weight_kg, height_m

# CONFIG
BMI_blueprint = Blueprint('BMI', __name__, template_folder='templates/features')

@BMI_blueprint.route('/bmi', methods=['GET', 'POST'])
@login_required
@requires_roles('user')
def bmi():
    form = BMIForm()
    r_form = BMIResultForm()
    if form.validate_on_submit():
        #gets the units for the height and weight from the form
        h_choice = form.h_units.data
        w_choice = form.w_units.data
        #gets the value for the height and weight from the form, making them a float type
        H = float(form.height.data)
        W = float(form.weight.data)
        #calls the functions to return the height in metres and weight in kg so this can be saved in the database
        weight = weight_kg(W, w_choice)
        height = height_m(H, h_choice)
        #calculates the bmi and saves it to the bmi result form
        r_form.bmi.data = bmi_calc(H, W, h_choice, w_choice)


        with app.app_context():
            #saves the users id, bmi, height and weight in the database
            new_bmi = BMI(user_id=current_user.id, bmi=r_form.bmi.data, height=height, weight=weight)
            db.session.add(new_bmi)
            db.session.commit()

        #redirects the user to the bmi result page with their bmi displayed on it
        return render_template('features/trackers/bmi_result.html', form=r_form, bmi=r_form.bmi.data)

    #reloads the page and the form if the form doesnt validate
    return render_template('features/trackers/bmi.html', form=form)

CalorieCounter/views.py
from app import db, app
from models import Calories, CalorieGoal
from CalorieCounter.forms import CalCalcForm, CounterForm, CalcResultForm, CounterResult
from flask import Blueprint, render_template, request, flash
from flask_login import current_user, login_required
from users.views import requires_roles
from CalorieCounter.calc_cals import calculate_calories

# CONFIG
calorie_blueprint = Blueprint('calories', __name__, template_folder='templates/features')


@calorie_blueprint.route('/view', methods=['GET', 'POST'])
@login_required
@requires_roles('user')
def calorie_counter():
    form = CounterForm()
    r_form = CounterResult()
    if form.validate_on_submit():
        entry_date = form.entry_date.data
        calories = float(form.calories.data)
        # checks which button is pressed and gives the correct action
        if request.form.get('action') == 'Add to existing entry':
            edit(entry_date, calories)
            return render_template('features/trackers/calorie_counter_result.html', form=r_form)
        elif request.form.get('action') == "Create new entry":
            new_entry(entry_date, calories)
            return render_template('features/trackers/calorie_counter_result.html', form=r_form)
        elif request.form.get('action') == "View all entries":
            view()

    # reloads the page and the form if the form doesnt validate
    return render_template('features/trackers/calorie_counter.html', form=form)


@calorie_blueprint.route('/view_entries', methods=['POST'])
@login_required
@requires_roles('user')
def view():
    form = CounterForm()
    # gets all the entries for the current user id
    entries = Calories.query.filter_by(user_id=current_user.id).all()

    if len(entries) == 0:
        # displays error message if the user has no entries
        flash("You have no calorie data in the database")
        return render_template("features/trackers/error.html")
    else:
        # displays the entries for the user
        return render_template("features/trackers/calorie_counter.html", form=form, entries=entries)


def edit(entry_date, new_entry):
    with app.app_context():
        # loops through the data in the calories table that belongs to the current user and has the given entry date
        for row in db.session.query(Calories).filter_by(user_id=current_user.id, entry_name=entry_date):
            # when it finds this data is takes the calorie value
            existing_cals = row.daily_calories
        # saves this whole row to object
        object = Calories.query.filter_by(user_id=current_user.id, entry_name=entry_date).first()
        # if this object doesnt existing an error message is displayed
        if object == None:
            flash("Date doesn't exist in the database, please try another date or create an entry for this date")
        else:
            # if this object exists, the calories are updated
            db.session.delete(object)
            db.session.commit()
            new_cals = existing_cals + new_entry
            new_cal = Calories(user_id=current_user.id, entry_name=entry_date, daily_calories=new_cals)
            db.session.add(new_cal)
            db.session.commit()
            flash("Your data has been updated successfully")


def new_entry(entry_date, calories):
    with app.app_context():
        # searches the database to see if the entry date for that user already exists
        object = Calories.query.filter_by(user_id=current_user.id, entry_name=entry_date).first()

        if object == None:
            # if there isn't an existing entry with this entry date for this user it will create a new object and add it to the database
            new_cal = Calories(user_id=current_user.id, entry_name=entry_date, daily_calories=calories)
            db.session.add(new_cal)
            db.session.commit()
            flash("Your data has been added to the database successfully")
        else:
            # if there is an existing entry with this entry date the user will be shown an error message
            flash("Date already exists in the database, try adding to this date or creating an entry for another date")


@calorie_blueprint.route('/calculator', methods=['GET', 'POST'])
@login_required
@requires_roles('user')
def calorie_calculator():
    form = CalCalcForm()
    r_form = CalcResultForm()
    if form.validate_on_submit():
        # gets the values for protein, fat and carbohydrates from the user form and gives them the type float
        protein = float(form.protein.data)
        fat = float(form.fat.data)
        carbs = float(form.carbohydrate.data)

        # calculates the total calories given their inputs
        total_cals = calculate_calories(protein, fat, carbs)

        # saves this value to the form for the results page
        r_form.calories.data = total_cals

        with app.app_context():
            # cerates a new object with the users calories and saves it to  the database
            new_cal = CalorieGoal(user_id=current_user.id, calorie_goal=total_cals)
            db.session.add(new_cal)
            db.session.commit()

        # redirects the user to the calculation result with the result form and the calculated calories for the user
        return render_template('features/trackers/calc_result.html', form=r_form, calories=r_form.calories.data)
    # if the form doesn't validate, the page is reloaded with the original form
    return render_template('features/trackers/calories.html', form=form)

PeriodTracker/views.py
import datetime
from datetime import timedelta
from app import db
from models import Period
from PeriodTracker.forms import PeriodForm
from PeriodTracker.forms import NextPeriodForm
from flask import Blueprint, render_template
from flask_login import current_user, login_required
from users.views import requires_roles

# Define the name of blueprint and get the path of template
period_blueprint = Blueprint('period_tracker', __name__, template_folder='templates/features')


# Add the route of blueprint and define the methods
@period_blueprint.route('/period_tracker', methods=['GET', 'POST'])
# Only logged-in users can access
@login_required
# Add RBAC to make this feature only can be accessed by user role
@requires_roles('user')
# Define the period tracker function
def period_tracker():
    # Define the forms for input info and display result
    p_form = PeriodForm()
    r_form = NextPeriodForm()
    # If user submit the period information form
    if p_form.validate_on_submit():
        # Get the current period info from the period form
        start_date = p_form.start_date.data
        end_date = p_form.end_date.data
        period_duration = p_form.period_duration.data
        period_cycle = p_form.period_cycle.data
        # Call the calculate function to get the calculated results
        next_start_date, next_end_date, ovulation = calculate_next_period(start_date, end_date, period_duration,
                                                                          period_cycle)

        # Set the next period info to the next period form
        r_form.next_start_date.data = next_start_date
        r_form.next_end_date.data = next_end_date
        r_form.ovulation.data = ovulation

        # Store the period information to the database
        period = Period(user_id=current_user.id, start_date=start_date, end_date=end_date,
                        period_duration=period_duration, period_cycle=period_cycle, next_start_date=next_start_date,
                        next_end_date=next_end_date, ovulation=ovulation)
        db.session.add(period)
        db.session.commit()

        # If the form submit, redirect users to the period_result template to display the result
        return render_template('features/trackers/period_result.html', form=r_form,
                               next_start_date=r_form.next_start_date.data, next_end_date=r_form.next_start_date.data,
                               ovulation=r_form.next_start_date.data)

    # Redirect users to the period template for the next calculate
    return render_template('features/trackers/period.html', form=p_form)


# Only logged-in users can access
@login_required
# Add RBAC to make this feature only can be accessed by user role
@requires_roles('user')
# Define the function to calculate next period
def calculate_next_period(start_date, end_date, period_duration, period_cycle):
    next_start_date = start_date + timedelta(days=period_cycle)
    next_end_date = end_date + timedelta(days=period_cycle)
    ovulation = next_start_date - timedelta(days=14)
    return next_start_date, next_end_date, ovulation

RSS/views.py
from flask import render_template
import feedparser
from flask import Blueprint

news_blueprint = Blueprint('news', __name__, template_folder='templates/features')


@news_blueprint.route('/features/news', methods=['get'])
def news():
    feed = feedparser.parse('https://www.england.nhs.uk/feed/')
    articles = feed.entries[:10]
    return render_template('features/news.html', articles=articles)

templates/main/index.html
{% extends "base.html" %}

{% block content %}
  <div class="full-width padding">
    <div class="news-container" id="news-container">
      <button class="one">
        <img src="static/resources/search.svg">
        <a href="{{ url_for('news.news') }}">Explore more
        </a>
        <img src="/static/resources/fi-rr-arrow-right.svg">
      </button>
      <!-- <div class="news-box">
        <h2>Title of Article</h2>
        <p>Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc Desc </p>
      </div> -->
    </div>
    <ul class="feature-quick-access">
      <li>
        <button class="two">
          <img src="/static/resources/bmi.svg" alt="bmi">
          <a href="{{ url_for('BMI.bmi') }}">BMI Calculator</a>
        </button>
      </li>
      <li>
        <button class="two">
          <img src="/static/resources/calculator.svg" alt="calculator">
          <a href="{{ url_for('calories.calorie_calculator') }}">Calorie Calculator</a>
        </button>
      </li>
      <li>
        <button class="two">
          <img src="/static/resources/calorie.svg" alt="calorie">
          <a href="{{ url_for('calories.calorie_counter') }}">Calorie Counter</a>
        </button>
      </li>
      <li>
        <button class="two">
          <img src="/static/resources/period.svg" alt="period">
          <a href="{{ url_for('period_tracker.period_tracker') }}">Period Tracker</a>
        </button>
      </li>
    </ul>
  </div>

  <!-- api reference: https://gnews.io/docs/v4?javascript#top-headlines-query-parameters -->
  <script>
    var apikey = 'c85d9b57e2349444885af3a5da2ad676';
    var category = 'health';
    var url = 'https://gnews.io/api/v4/top-headlines?category=' + category + '&lang=en&country=us&max=10&apikey=' + apikey;

    fetch(url)
      .then(function (response) {
        return response.json();
      })
      .then(function (data) {
        var articles = data.articles;
        var newsContainer = document.getElementById('news-container');

        for (var i = 0; i < Math.min(3, articles.length); i++) {
          var article = articles[i];
          console.log("Title: " + article.title);
          console.log("Description: " + article.description);
          console.log("Published At: " + article.publishedAt);
          console.log("Picture:" + article.img);

          var newsBox = document.createElement('div');
          newsBox.classList.add('news-box');

          var newsTitle = document.createElement('h2');
          newsTitle.textContent = article.title;

          var newsDescription = document.createElement('p');
          newsDescription.textContent = article.description;

          var newspublishedAt = document.createElement('p');
          newspublishedAt.textContent = article.publishedAt;

          // var newsPicture = document.createElement('pic');
          // newsPicture.img.add('news-pic');
          // newsPicture.img = article.img;

          newsBox.appendChild(newsTitle);
          newsBox.appendChild(newsDescription);
          newsBox.appendChild(newspublishedAt);
          // newsBox.appendChild(newsPicture);

          newsContainer.appendChild(newsBox);
        }
      });
  </script>
{% endblock %}