Quiz/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField


class QuizForm(FlaskForm):
    """
    Form class for the quiz form.

    Attributes:
        number_of_questions: SelectField to choose the number of questions.
        submit: SubmitField to submit the form.
    """
    number_of_questions = SelectField('Select the number of questions:',
                                      choices=[(str(i), str(i)) for i in range(5, 16)])
    submit = SubmitField('Begin')

Share/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, SubmitField, StringField, SelectField
from wtforms.validators import DataRequired
from flask_share import Share
from app import app



class share_form(FlaskForm):
    blog = StringField()

Quiz/views.py
"""
Quiz Views

This file defines a Flask blueprint for handling the Quiz page for retrieving
questions and rendering the quiz.
"""


import json

from flask import Blueprint, render_template
from app import app
from models import Question
import random
from Quiz.forms import QuizForm

quiz_blueprint = Blueprint('Quiz', __name__, template_folder='templates/features')


@quiz_blueprint.route('/quiz', methods=['GET', 'POST'])
def quiz():
    """
    Renders the quiz template and handles form submission.

    Returns:
        Rendered template 'features/quiz.html' with form and questions data.
    """
    form = QuizForm()

    if form.validate_on_submit():
        num_questions = int(form.number_of_questions.data)
        questions = retrieve_random_questions(num_questions)

        return render_template('features/quiz.html',
                               form=form,
                               questions=questions,
                               questions_json=json.dumps(questions))

    return render_template('features/quiz.html', form=form)


def retrieve_questions():
    """
    Retrieves all questions from the database.

    Returns:
        List of all questions.
    """
    with app.app_context():
        return Question.query.all()


def retrieve_random_questions(num_questions):
    """
    Retrieves a random selection of questions from the database.

    Args:
        num_questions: Number of questions to retrieve.

    Returns:
        List of formatted random questions.
    """
    all_questions = retrieve_questions()
    random_questions = random.sample(all_questions, num_questions)
    formatted_questions = []

    for question in random_questions:
        formatted_question = {
            'text': question.question,
            'choices': [question.answer_one,
                        question.answer_two,
                        question.answer_three,
                        question.answer_four],
            'correct_answer': question.correct_answer
        }
        formatted_questions.append(formatted_question)

    return formatted_questions

SearchDiseases/views.py
"""
Search Disease Views

This file defines a Flask blueprint for handling the search functionality for
diseases and conditions, allowing users to search the NHS website and retrieve
and view relevant data.
"""


from flask import render_template, request, Blueprint
from SearchDiseases.search import NHSWebsiteCrawler


search_blueprint = Blueprint('search', __name__, template_folder='templates/features')


@search_blueprint.route('/search_disease', methods=['GET', 'POST'])
def search_disease():
    """
    Handles the search functionality for diseases.

    Returns:
        string: The rendered HTML template with search results.

    Notes:
        - If the request method is 'POST', the search term is extracted from the form data.
        - An instance of NHSWebsiteCrawler is created to search and retrieve data from the NHS website.
        - The search term is used to search the NHS website.
        - If a match is found, the data related to the search term is retrieved.
        - The search results are rendered in the 'features/search.html' template.
    """
    if request.method == 'POST':
        search_term = request.form['search_term']

        url = 'https://www.nhs.uk/conditions/'
        nhs = NHSWebsiteCrawler(url)

        is_successful, result = nhs.search_website(search_term)

        if is_successful:
            result = nhs.retrieve_data(search_term)

        return render_template('features/search.html',
                               search_term=search_term,
                               result=result,
                               is_successful=is_successful)

    return render_template('features/search.html')

Share/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, Markup, request



share_blueprint = Blueprint('Share', __name__, template_folder='templates/features')

@share_blueprint.route('/share', methods=['GET', 'POST'])
def share_run():
    pass

health/views.py
"""
Health Views

This file defines a Flask blueprint for handling the health page for displaying
health explanations, tips, and facts, also providing the function to display
random conditions from a CSV file.
"""


from flask import Blueprint, render_template, request, redirect, url_for
import csv
import os
import random
import re
from collections import OrderedDict


health_blueprint = Blueprint('health', __name__, template_folder='templates/features')


@health_blueprint.route('/health', methods=['GET', 'POST'])
def health():
    """
    Handles the health route for displaying disease information and symptoms.

    Returns:
        string: The rendered HTML template with disease information.

    Notes:
        - If the request method is 'POST', redirects back to the health route.
        - Randomly selects four diseases from the CSV file and retrieves their information.
        - Disease information is processed and stored in a list.
        - The list of disease information is passed to the 'features/health.html' template for rendering.
    """
    if request.method == 'POST':
        return redirect(url_for('health'))

    all_disease = []
    random_list = random.sample(read_csv_columns(os.path.dirname(__file__) + "/disease.csv", 1), 4)
    dict_ = sym_dict_(os.path.dirname(__file__) + "/disease.csv")

    for disease in random_list:
        d_list = []
        sym = (get_symptoms_from_data(disease))
        sym_convert(sym, dict_)
        d_list.extend((get_name(disease), split_data_decs(disease), OrderedDict.fromkeys(sym)))
        all_disease.append(d_list)

    return render_template('features/health.html', result=all_disease)


def read_csv_columns(csv_file, column_number):
    """
    Read the specified columns from a CSV file.

    Args:
        csv_file (str): The path to the CSV file.
        column_number (int): The number of columns to read.

    Returns:
        list: A list of columns read from the CSV file.
    """
    columns = []
    with open(csv_file, 'r', encoding='utf-8') as file:
        reader = csv.reader(file)
        for row in reader:
            columns.append(row[:column_number])  # Add first three columns to the list
    return columns


def get_symptoms(data):
    """
    Extract symptoms from the data.

    Args:
        data (list): The data containing symptoms.

    Returns:
        list: A list of symptoms extracted from the data.
    """
    symptoms = []
    for item in data:
        if 'symptoms' in item:
            symptoms.append(item['symptoms'])
    return symptoms


def sym_dict_(csv_file):
    """
    Create a dictionary of symptoms.

    Args:
        csv_file (str): The path to the CSV file.

    Returns:
        dict: A dictionary of symptoms.
    """
    dict_ = {}
    with open(csv_file, 'r', encoding='utf-8') as file:
        for line in file:
            line = line[1:-1]
            key, value = line[0:].split(",")[:2]
            dict_[key] = value
    return dict_


def split_data_decs(d):
    """
    Split the data description.

    Args:
        d (list): The data containing the description.

    Returns:
        str: The split data description.
    """
    element_parts = d[0].split("],", 1)
    return re.sub(r'[\s"]+', ' ', element_parts[1].strip())


def sym_convert(sym_list, dict_):
    """
    Convert symptom names using a dictionary.

    Args:
        sym_list (list): The list of symptoms to convert.
        dict_ (dict): The dictionary containing symptom conversions.
    """
    for i in range(len(sym_list)):
        if sym_list[i] in dict_:
            sym_list[i] = dict_[sym_list[i]]


def get_symptoms_from_data(data):
    """
    Extracts symptoms from the provided data.

    Args:
        data (list): A list containing the data.

    Returns:
        list: A list of symptoms extracted from the data.
    """
    start_index = data[0].index('[{')
    end_index = data[0].index('}]')
    parsed_data = eval(data[0][start_index:end_index + 2])

    symptoms_list = get_symptoms(parsed_data)

    return symptoms_list


def get_name(disease):
    """
    Retrieves the name of the disease from the provided disease data.

    Args:
        disease (list): A list containing the disease data.

    Returns:
        str: The name of the disease.
    """
    disease = disease[0]
    disease = disease.split(",")
    return disease[1]

templates/features/health.html
{% extends "base.html" %}

{% block content %}
  <div class="full-width padding">
    <div class="container content">
      <div class="content content-text">
        <div class="content">
          <h1>What is Health and Wellbeing?</h1>
          <p>
            Health and wellbeing is the state of one's physical, mental, or emotional condition and the lifestyle surrounding it. Rather than it being the absence of disorders, disabilities, or negative conditions, it is the improvement towards the quality of living in order to live a long, productive, and positive life.
          </p>
          <h3>Physical Health</h3>
          <p>
            Physical health means taking care of our body. It includes things like staying at a healthy weight, doing regular exercise, getting enough sleep, and eating nutritious food. When we are physically healthy, we have the energy to do things and are less likely to get sick.
          </p>
          <h3>Mental Health</h3>
          <p>
            Mental health is about how we feel and think. It's important to have good mental health so that we can handle stress, have positive relationships, and feel good about ourselves. It's normal to have ups and downs, but taking care of our mental health helps us stay balanced and happy.
          </p>
          <h3>Social Wellbeing</h3>
          <p>
            Social wellbeing is all about our relationships with other people. It's about having good connections with friends, family, and our community. When we feel connected and supported, it makes us feel happier and less lonely.
          </p>
        </div>
        <div>
          <div class="box-info content">
            <h2>Did you know?</h2>
            <p>
              Studies have shown that people who maintain strong social connections tend to live longer and have better overall health!
            </p>
          </div>
        </div>
      </div>

      <div class="content content-text">
        <div class="content">
          <h1>Why does this all matter?</h1>
          <p>
            It's important to focus on health and wellbeing because they help us live our best lives. When we take care of ourselves, it keeps our body and mind working well. It helps us handle challenges and enjoy life more. It also makes it easier for us to support and contribute to our communities.
          </p>
        </div>
        <div>
          <div class="box-info content">
            <h2>Tip!</h2>
            <p>
              Getting regular health check-ups by scheduling routine check-ups and screenings can detect any potential issues early, and get the appropriate preventive care, improving your overall quality of life!
            </p>
          </div>
        </div>
      </div>

      <div class="content content-text">
        <div class="content">
          <h1>How we are here to help</h1>
          <p>
            The Health Lab is here to help you learn more about health and wellbeing. We provide easy-to-use trackers, tips, and health and advice searchers to help you make choices that will improve your health and wellbeing. By learning about these things and making small changes in our daily lives, we can feel better and live happier lives.
          </p>
        </div>
      </div>

      <div class="content">
        <h1>Help Lines & Advice</h1>
        <div class="container content helplines urgent">
          <h2>Call 999 or go to A&E NOW if:</h2>
          <p><b>
            Is someone's life is at risk or do you do not feel you can keep yourself or someone else safe?
          </b></p>
          <p><b>
            A mental health emergency should be taken as seriously as a physical one. You will not be wasting anyone's time.
          </b></p>
        </div>
        <div class="container content helplines">
          <h2>Call 111 or book a GP appointment if:</h2>
          <p>
            You have any non-emergency enquiries or any non-urgent health concerns.
          </p>
          <p>
            This service will be able to guide you to the right resource or service to fit your needs
          </p>
        </div>
        <div class="container content helplines">
          <h2>The Samaritans</h2>
          <p>
            You have any non-emergency enquiries or any non-urgent health concerns.
          </p>
          <p>
            This service will be able to guide you to the right resource or service to fit your needs
          </p>
        </div>
        <div class="container content helplines">
          <h2>Shout Crisis Help Line</h2>
          <p>
            Text "SHOUT" to 85258 to contact the Shout Crisis Text Line, or text "YM" if you're under 19
          </p>
        </div>
        <div class="container content helplines">
          <h2>Childline</h2>
          <p>
            If you're under 19, you can also call 0800 1111 to talk to Childline. The number will not appear on your phone bill.
          </p>
        </div>
      </div>
    </div>
    <div class="container results"  id="conditions-symptoms">
      <h1>Example Conditions and Symptoms</h1>
      <button onclick="window.location.href='/health'" class="btn">Generate New Example</button>
      {% for disease in result %}
      <div class="condition-result">
        <h2>{{ disease[0] }}</h2>
        <p>{{ disease[1] }}</p>
        <h3>Symptoms:</h3>
        <ul>
          {% for symptom in disease[2] %}
          <li>{{ symptom }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

templates/features/news.html
{% extends "base.html" %}

{% block content %}
  <div class="full-width padding">
      <div class="news-container" id="news-container">
        <h1>NHS News Blog</h1>
        {% for article in articles %}
          <div class="news-box content">
            <b><a href="{{ article.link }}">{{ article.title }}</a></b><br>
            <span>{{ article.published }}</span>
            <p>{{ article.summary }}</p>
          </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/features/quiz.html
{% extends "base.html" %}

{% block content %}
<div class="full-width full-page padding">
    <div class="container form-container">
        <h1>Quiz</h1>
        {% if form %}
            <form  class="form" method="post">
                <div>
                    {{ form.csrf_token() }}
                    <div>
                        {{ form.number_of_questions }}
                        {% for error in form.number_of_questions.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>{{ form.submit() }}</div>
            </form>
        {% endif %}
    </div>
    {% if questions %}

        <div id="quiz-container" class="quiz-container revealed">
            <!-- CODE ITERATE OVER QUESTIONS TO DISPLAY -->
            {% set counter = 0 %}
            {% for question in questions %}
                {% set counter = loop.index %}
                <div>
                    <h3>{{ question['text'] }}</h3>
                    {% for choice in question['choices'] %}
                        <div>
                            <input type="radio" name="answer_{{ counter }}" value="{{ loop.index }}">
                            <label>{{ choice }}</label>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button id="submit-answers" type="button" class="button one">Submit Answers</button>
        </div>
    {% endif %}

    <div id="quiz-result-container" class="container quiz-container">
        <h1>Quiz Result</h1>
        <h3 id="quiz-score"></h3>
        <button id="redo-quiz" class="button one">Redo Quiz</button>
      </div>
</div>

<script>
    // Wait for the DOM content to load
    window.addEventListener('DOMContentLoaded', function() {
        console.log("JavaScript code executed");
        const quizContainer = document.getElementById("quiz-container");
        const quizResultContainer = document.getElementById("quiz-result-container");
        const quizScore = document.getElementById("quiz-score");
        const redoQuizButton = document.getElementById("redo-quiz");
        const submitButton = document.getElementById("submit-answers");
        const quiz_questions = JSON.parse('{{ questions_json|safe }}');


        function calculateScore(questions) {
            let score = 0;
            const checkedElements = document.querySelectorAll('input:checked');

            for (let i = 0; i < questions.length; i++) {
                    if (checkedElements[i].value == questions[i]['correct_answer']) {
                        score++;
                    }
            }
            return score;
        }


        function showQuizResult(score, totalQuestions) {
            quizContainer.classList.toggle('revealed')
            quizScore.textContent = "You scored " + score + " out of " + totalQuestions + " questions.";
            quizResultContainer.classList.toggle('revealed')
        }

        submitButton.addEventListener("click", function() {
            if (document.querySelectorAll('input:checked').length !== quiz_questions.length) {
                alert('Provide an answer for ALL questions')
            } else {
                const score = calculateScore(quiz_questions);
            showQuizResult(score, quiz_questions.length);
            }
        });

        redoQuizButton.addEventListener("click", function() {
            quizResultContainer.classList.toggle('revealed')
        });
    });
</script>
{% endblock %}

templates/features/search.html
{% extends "base.html" %}

{% block content %}
    <div class="full-width full-page padding">
        <div class="container form-container">
            <h1>Search</h1>
            <form class="search-bar in-page" method="POST" action="{{ url_for('search.search_disease') }}">
                <input type="text" name="search_term" placeholder="Search...">
            </form>

            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification">
                        {{ messages[0] }}.
                    </div>
                {% endif %}
            {% endwith %}
        </div>

        {% if search_term != null %}
            <div class="container results">
                <h1>Results from NHS: {{ search_term|capitalize }}</h1>
                <div>
                    {% if is_successful %}
                        {{ result|safe }}
                    {% else %}
                        <h2>There were no found matches.</h2>
                        <h4>Similar results:</h4>
                        {% for similar_result in result %}
                            <form class="similar-match" method="POST" action="{{ url_for('search.search_disease') }}">
                                <button class="nav-hover" type="submit" name="search_term" value="{{ similar_result[0] }}">> <u><i>{{ similar_result[0] }}</i></u></button>
                            </form>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/features/share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form  class="form" method="get">
        <div>
            {{ form.csrf_token() }}
            <div>
                {{ form.blog(class="input", placeholder="Begin your blog") }}
                {% for error in form.entry_date.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        </div>


    </form>
</body>
</html>