BMI/views.py
from models import BMI
from app import db, app
from flask_login import current_user,login_required
from BMI.forms import BMIForm, BMIResultForm
from flask import Blueprint, render_template
from users.views import requires_roles
from BMI.calc_bmi import bmi_calc, weight_kg, height_m

# CONFIG
BMI_blueprint = Blueprint('BMI', __name__, template_folder='templates/features')

@BMI_blueprint.route('/bmi', methods=['GET', 'POST'])
@login_required
@requires_roles('user')
def bmi():
    form = BMIForm()
    r_form = BMIResultForm()
    if form.validate_on_submit():
        #gets the units for the height and weight from the form
        h_choice = form.h_units.data
        w_choice = form.w_units.data
        #gets the value for the height and weight from the form, making them a float type
        H = float(form.height.data)
        W = float(form.weight.data)
        #calls the functions to return the height in metres and weight in kg so this can be saved in the database
        weight = weight_kg(W, w_choice)
        height = height_m(H, h_choice)
        #calculates the bmi and saves it to the bmi result form
        r_form.bmi.data = bmi_calc(H, W, h_choice, w_choice)


        with app.app_context():
            #saves the users id, bmi, height and weight in the database
            new_bmi = BMI(user_id=current_user.id, bmi=r_form.bmi.data, height=height, weight=weight)
            db.session.add(new_bmi)
            db.session.commit()

        #redirects the user to the bmi result page with their bmi displayed on it
        return render_template('features/trackers/bmi_result.html', form=r_form, bmi=r_form.bmi.data)

    #reloads the page and the form if the form doesnt validate
    return render_template('features/trackers/bmi.html', form=form)

Quiz/views.py
"""
Quiz Views

This file defines a Flask blueprint for handling the Quiz page for retrieving
questions and rendering the quiz.
"""


import json

from flask import Blueprint, render_template
from app import app
from models import Question
import random
from Quiz.forms import QuizForm

quiz_blueprint = Blueprint('Quiz', __name__, template_folder='templates/features')


@quiz_blueprint.route('/quiz', methods=['GET', 'POST'])
def quiz():
    """
    Renders the quiz template and handles form submission.

    Returns:
        Rendered template 'features/quiz.html' with form and questions data.
    """
    form = QuizForm()

    if form.validate_on_submit():
        num_questions = int(form.number_of_questions.data)
        questions = retrieve_random_questions(num_questions)

        return render_template('features/quiz.html',
                               form=form,
                               questions=questions,
                               questions_json=json.dumps(questions))

    return render_template('features/quiz.html', form=form)


def retrieve_questions():
    """
    Retrieves all questions from the database.

    Returns:
        List of all questions.
    """
    with app.app_context():
        return Question.query.all()


def retrieve_random_questions(num_questions):
    """
    Retrieves a random selection of questions from the database.

    Args:
        num_questions: Number of questions to retrieve.

    Returns:
        List of formatted random questions.
    """
    all_questions = retrieve_questions()
    random_questions = random.sample(all_questions, num_questions)
    formatted_questions = []

    for question in random_questions:
        formatted_question = {
            'text': question.question,
            'choices': [question.answer_one,
                        question.answer_two,
                        question.answer_three,
                        question.answer_four],
            'correct_answer': question.correct_answer
        }
        formatted_questions.append(formatted_question)

    return formatted_questions

RSS/views.py
from flask import render_template
import feedparser
from flask import Blueprint

news_blueprint = Blueprint('news', __name__, template_folder='templates/features')


@news_blueprint.route('/features/news', methods=['get'])
def news():
    feed = feedparser.parse('https://www.england.nhs.uk/feed/')
    articles = feed.entries[:10]
    return render_template('features/news.html', articles=articles)

admin/views.py
# IMPORTS
from flask import Blueprint, render_template
from models import User
from users.views import requires_roles


admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admin_blueprint.route('/admin')
@requires_roles('admin')
def admin():
    return render_template('admin/admin.html')


@admin_blueprint.route('/view_all_users', methods=['POST'])
@requires_roles('admin')
def view_all_users():
    current_users = User.query.filter_by(role='user').all()

    return render_template('admin/admin.html', current_users=current_users)


@admin_blueprint.route('/logs', methods=['POST'])
@requires_roles('admin')
def logs():
    with open("health.log", "r") as f:
        content = f.read().splitlines()[-10:]
        content.reverse()

    return render_template('admin/admin.html', logs=content)

templates/503.html
{% extends "base.html" %}

{% block content %}

    <!--503 - Service Unavailable Error-->
    <div class="error-message">
        <div>
            <h2 class="title is-2">Service unavailable</h2>
            <p>Server is currently unavailable to handle your request</p>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <script src="/static/scripts/scripts.js" defer></script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name=”robots” content="index, nofollow">
  <link rel="stylesheet" href="/static/css/main.css"/>
  <title>The Health Lab</title>
   <link rel="icon" type="image/png" href="/static/resources/favicon.png"/>
</head>

<nav class="full-width">
  <div class="nav">
    <img src="/static/resources/lab-flask.svg" alt="Organisation Logo" class="logo">
    <a href="{{ url_for('index') }}" class="title"><h2>The Health Lab</h2></a>
    <ul class="nav-desktop">
      <li><a href="{{ url_for('health.health') }}" class="link nav-hover">Health</a></li>
      <li><a href="{{ url_for('news.news') }}" class="link nav-hover">News</a></li>
      <li><a href="{{ url_for('Quiz.quiz') }}" class="link nav-hover">Quiz</a></li>
      <li class="dropdown">
        <a href="#" class="link nav-hover">Track</a>
        <ul class="dropdown-list">
          <li><a href="{{ url_for('BMI.bmi') }}" class="link nav-hover">BMI Calculator</a></li>
          <li><a href="{{ url_for('calories.calorie_calculator') }}" class="link nav-hover">Calorie Calculator</a></li>
          <li><a href="{{ url_for('calories.calorie_counter') }}" class="link nav-hover">Calorie Counter</a></li>
          <li><a href="{{ url_for('period_tracker.period_tracker') }}" class="link nav-hover">Period Tracker</a></li>
        </ul>
        <div class="dropdown-icon"></div>
      </li>
    </ul>
    <ul class="nav-desktop">
      {% if current_user.is_authenticated and current_user.role == 'admin' %}
        <li><a href="{{ url_for('admin.admin') }}" class="link nav-hover">Admin</a></li>
      {% endif %}

      {% if current_user.is_authenticated and (current_user.role == 'user' or
                                               current_user.role == 'admin') %}
        <li><a href="{{ url_for('users.account') }}" class="link nav-hover">Account</a></li>
      {% endif %}

      {% if current_user.is_authenticated and (current_user.role == 'user' or
                                               current_user.role == 'admin') %}
        <li><a href="{{ url_for('users.logout') }}" class="link nav-hover">Logout</a></li>
      {% endif %}

      {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('users.login') }}" class="link nav-hover">Login</a></li>
      {% endif %}

      {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('users.register') }}" class="link nav-hover">Sign-up</a></li>
      {% endif %}

    </ul>
    <form class="search-bar" method="POST" action="{{ url_for('search.search_disease') }}">
        <input type="text" name="search_term" placeholder="Search...">
    </form>
    <div class="menu-icon">
      <span class="one"></span>
      <span class="two"></span>
    </div>
  </div>
  <div id="nav-mobile" class="nav-mobile">
    <ul>
      <li><a href="{{ url_for('health.health') }}" class="link nav-hover">Health</a></li>
      <li class="dropdown">
        <a href="#" class="link nav-hover">Track</a>
        <ul class="dropdown-list">
          <li><a href="{{ url_for('BMI.bmi') }}" class="link nav-hover">BMI Calculator</a></li>
          <li><a href="{{ url_for('calories.calorie_calculator') }}" class="link nav-hover">Calorie Calculator</a></li>
          <li><a href="{{ url_for('calories.calorie_counter') }}" class="link nav-hover">Calorie Counter</a></li>
          <li><a href="{{ url_for('period_tracker.period_tracker') }}" class="link nav-hover">Period Tracker</a></li>
        </ul>
        <div class="dropdown-icon"></div>
      </li>

      <li><a href="{{ url_for('Quiz.quiz') }}" class="link nav-hover">Quiz</a></li>
      <li><a href="{{ url_for('news.news') }}" class="link nav-hover">News</a></li>

      {% if current_user.is_authenticated and current_user.role == 'admin' %}
        <li><a href="{{ url_for('admin.admin') }}" class="link nav-hover">Admin</a></li>
      {% endif %}

      {% if current_user.is_authenticated and (current_user.role == 'user' or
                                               current_user.role == 'admin') %}
        <li><a href="{{ url_for('users.account') }}" class="link nav-hover">Account</a></li>
      {% endif %}

      {% if current_user.is_authenticated and (current_user.role == 'user' or
                                               current_user.role == 'admin') %}
        <li><a href="{{ url_for('users.logout') }}" class="link nav-hover">Logout</a></li>
      {% endif %}

      {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('users.login') }}" class="link nav-hover">Login</a></li>
      {% endif %}

      {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('users.register') }}" class="link nav-hover">Sign-up</a></li>
      {% endif %}

      <li><a href="{{ url_for('search.search_disease') }}" class="link nav-hover">Search</a></li>
    </ul>
  </div>
</nav>

<body>
  {% block content %}
  {% endblock %}
</body>
<footer>
    <div class="footer-section">
      <a href="{{ url_for('index') }}" class="title"><h3>The Health Lab</h3></a>
      <p>@Copyright 2023<p>
    </div>

    <div class="footer-section">
      <a href="#"><h3>Contact us</h3></a>
      <p>Email: thehealthlab2023@outlook.com</p>
    </div>

    <div class="footer-section">
      <a href="#"><h3>Follow us</h3></a>
      <script src="/static/scripts/insta.js"></script>
      <a href="https://www.instagram.com/" target="_blank"><img src="/static/resources/instagram.svg"></a>
      <script src="/static/scripts/facebook.js"></script>
      <a href="https://www.facebook.com/" target="_blank"><img src="/static/resources/facebook.svg"></a>
      <script src="/static/scripts/twitter.js"></script>
      <a href="https://twitter.com/" target="_blank"><img src="/static/resources/twitter.svg"></a>
    </div>
</footer>
</html>